spring.application.name=ActuatorSpring3
server.port=8909


#enabled
management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enabled=true
info.app.name=Actuator-demo
info.app.version=1.0
info.app.description=simple actuator example for fresher