spring.application.name=EmployeeManagement
server.port=8766

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:empdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# H2 Console (optional - access at http://localhost:8766/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
